version: '3'
services:
  open-cv:
      image: myopen-cv-image
      build:
        context: .
        dockerfile: Dockerfile
      container_name: open-cv
      network_mode: host
      privileged: true
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu,compute,utility,graphics,display]
      environment:
        - DISPLAY=${DISPLAY}
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ./:/home/SFND/
        - /run/user/1000/gdm/Xauthority:/root/.Xauthority:rw
      command: tail -F anything